---
- hosts: linux
  become: yes
  become_user: clacko
  roles:
    - role-beatinstall


#  tasks:
#    - name: test connection
#      ping:


#- hosts: windows
#  remote_user: clacko
#  tasks:
#    - name: test connection
#      win_ping:
#

