---
- hosts: linux
  become: yes
  become_user: clacko
  
  pre_tasks:
  get_url:
    url: https://www.elastic.co/downloads/past-releases/metricbeat-6-0-1
    dest: /tmp/metricbeat-6-0-1

  roles:
    - role-beatinstall

#  post_tasks:
#     - shell: vim /tmp/testfile2



#  tasks:
#    - name: test connection
#      ping:


#- hosts: windows
#  remote_user: clacko
#  tasks:
#    - name: test connection
#      win_ping:
#

