---
- hosts: localhost
  pre_tasks:
    - name: downloading files to jenkins
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.0.1-linux-x86_64.tar.gz
        dest: /tmp
  
- hosts: linux
  become: yes
  become_user: clacko
  roles:
    - role-beatinstall

#  post_tasks:
#     - shell: vim /tmp/testfile2



#  tasks:
#    - name: test connection
#      ping:


#- hosts: windows
#  remote_user: clacko
#  tasks:
#    - name: test connection
#      win_ping:
#

