---
- hosts: localhost
  become: yes
  become_user: clacko
  pre_tasks:
    - name: downloading files to jenkins
      get_url:
        url: "{{ source }}/{{ beats }}/{{ beats }}-6.0.1-x86_64.rpm"
        dest: /tmp
  
- hosts: linux
  become: yes
  roles:
    - role-beatinstall

- hosts: localhost
  become: yes
  become_user: clacko
  post_tasks:
    - name: deleting downloaded files
      shell: rm /tmp/*.rpm
