---
- hosts: localhost
  become: yes
  become_user: clacko
  pre_tasks:
    - name: downloading files to jenkins
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/{{ type }}beat/{{ type }}beat-6.0.1-x86_64.rpm
        dest: /tmp
  
- hosts: linux
  become: yes
  roles:
    - role-beatinstall
