---
- hosts: linux
  become: yes
  become_user: clacko
  
  pre_tasks:
     - shell: echo 'I":" Beginning to configure web server..'

  roles:
    - role-beatinstall

  post_tasks:
     - shell: echo 'I":" Done configuring nginx web server...'



#  tasks:
#    - name: test connection
#      ping:


#- hosts: windows
#  remote_user: clacko
#  tasks:
#    - name: test connection
#      win_ping:
#

