---
- hosts: linux
  become: yes
  become_user: clacko
  
#  pre_tasks:
#     - shell: vim /tmp/testfile

  roles:
    - role-beatinstall

#  post_tasks:
#     - shell: vim /tmp/testfile2



#  tasks:
#    - name: test connection
#      ping:


#- hosts: windows
#  remote_user: clacko
#  tasks:
#    - name: test connection
#      win_ping:
#

